[alias]
# Local opt-in helpers to compile/test with host-specific CPU tuning, setting blanket target-cpu=native can screw with GitHub CI
build-native = "build --config build.rustflags=['-C','target-cpu=native']"
test-native = "test --config build.rustflags=['-C','target-cpu=native']"
clippy-native = "clippy --config build.rustflags=['-C','target-cpu=native']"

[env]
SQLX_OFFLINE = "true"
